[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[rpc_endpoints]
celo_sepolia = "https://forno.celo-sepolia.celo-testnet.org"
celo = "https://forno.celo.org"

[etherscan]
celo_sepolia = { key = "${CELOSCAN_API_KEY}", chain = 11142220, url = "https://api-sepolia.celoscan.io/api" }
celo = { key = "${CELOSCAN_API_KEY}", chain = 42220, url = "https://api.celoscan.io/api" }
